version: '2'
services:
  mhip2-app:
    image: mhip2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - JDBC_URL=jdbc:postgresql://mhip2-postgresql:5432/mhip2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  mhip2-postgresql:
    extends:
      file: postgresql.yml
      service: mhip2-postgresql
